"""rename task fields and improve models

Revision ID: bb5be2d87a0f
Revises: a3f029e365a0
Create Date: 2026-06-05 00:19:11.332673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb5be2d87a0f'
down_revision: Union[str, Sequence[str], None] = 'a3f029e365a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('tasks_userid_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'users', ['user_id'], ['id'])
    op.drop_column('tasks', 'descreption')
    op.drop_column('tasks', 'userid')
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=15),
               existing_nullable=False)
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'username',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.add_column('tasks', sa.Column('userid', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('tasks', sa.Column('descreption', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_userid_fkey'), 'tasks', 'users', ['userid'], ['id'])
    op.drop_column('tasks', 'user_id')
    op.drop_column('tasks', 'description')
    # ### end Alembic commands ###
